### ISSUE TITLE
noaa.py looking for directories that aren't there

### ISSUE THREAD

**Issue by leiptrstormr** [cyber-atomus/autowx#5]
Directories /opt/wxsat and /opt/wxsat/logs aren't being created. Furthermore, users don't have write privileges for /opt. Why not automatically create these directories in autowx and kill two birds with one stone?

**Comment by cyber-atomus** [comment]
IMO users are expected to have minimum knowledge and configure the script correctly according to their expectations, create directories and subdirectories as they do it only once. 

Maybe in the future I'll do something like this - but at this point I'm not capable of developing autowx further - my laptop died, my station has too much issues etc.
